// ─── Permissions ───────────────────────────────────────────────────
export interface RoomPermissions {
  /** Whether viewers can play/pause/seek (default: true) */
  viewersCanControl: boolean;
  /** Whether viewers can send chat messages (default: true) */
  viewersCanChat: boolean;
}

// ─── User ──────────────────────────────────────────────────────────
export interface User {
  /** Unique session ID (generated on connect) */
  id: string;
  /** Display name shown in the room */
  displayName: string;
  /** Optional avatar URL or gravatar hash */
  avatar?: string;
  /** Persistent device/browser ID (generated by client) */
  peerId?: string;
  /** Connection status */
  connectionStatus?: "online" | "away";
  /** User's current local video timestamp (seconds) */
  videoTimestamp?: number;
  /** Latency in milliseconds (measured via ping/pong) */
  latency?: number;
}

// ─── Room ──────────────────────────────────────────────────────────
export interface RoomState {
  /** Deterministic room name (used as DO ID) */
  id: string;
  /** Human-readable room name */
  name: string;
  /** Connected users */
  users: User[];
  /** Current playback timestamp in seconds */
  currentTime: number;
  /** Whether playback is paused */
  paused: boolean;
  /** Playback rate (1 = normal) */
  playbackRate: number;
  /** Room permissions */
  permissions: RoomPermissions;
  /** Current shared video URL */
  videoUrl?: string;
}

// ─── Sync State ─────────────────────────────────────────────────────

/** Sync status for visual feedback */
export type SyncStatus =
  | "synced" // Within acceptable drift
  | "catching-up" // Using playback rate to catch up
  | "seeking" // Performing a hard seek
  | "behind" // Behind but within tolerance
  | "ahead"; // Ahead of room time

/** Detailed sync progress information */
export interface SyncProgress {
  /** Current sync status */
  status: SyncStatus;
  /** Drift from room time in seconds (positive = behind, negative = ahead) */
  drift: number;
  /** Target time we're syncing to */
  targetTime: number;
  /** Current local video time */
  currentTime: number;
  /** Progress percentage when catching up (0-100) */
  progressPercent: number;
  /** Estimated time to sync completion */
  estimatedTimeMs: number;
  /** Applied playback rate adjustment */
  appliedRate: number;
  /** Timestamp when sync started */
  syncStartTime: number;
}

// ─── WebSocket: Client → Server ────────────────────────────────────

export type WSClientMessage =
  | {
      type: "join";
      user: Omit<User, "id"> & { peerId: string };
      password?: string;
    }
  | { type: "leave" }
  | { type: "play"; currentTime: number }
  | { type: "pause"; currentTime: number }
  | { type: "seek"; currentTime: number }
  | { type: "chat"; message: string }
  | { type: "sync-request" }
  | { type: "playback-rate"; rate: number }
  | { type: "time-update"; currentTime: number }
  | { type: "kick"; userId: string }
  | {
      type: "update-permissions";
      permissions: Partial<RoomPermissions>;
    }
  | { type: "ping"; timestamp: number }
  | { type: "video-url"; url: string };

// ─── WebSocket: Server → Client ────────────────────────────────────

export type WSServerMessage =
  | { type: "user-joined"; user: User }
  | { type: "user-left"; userId: string }
  | { type: "play"; currentTime: number; userId: string }
  | { type: "pause"; currentTime: number; userId: string }
  | { type: "seek"; currentTime: number; userId: string }
  | { type: "chat"; message: string; userId: string; displayName: string }
  | { type: "sync"; room: RoomState }
  | { type: "error"; code: string; message: string; retryAfter?: number }
  | { type: "room-state"; room: RoomState; yourUserId: string }
  | { type: "playback-rate"; rate: number; userId: string }
  | { type: "kicked"; reason: string }
  | { type: "permissions-updated"; permissions: RoomPermissions }
  | { type: "user-time-update"; userId: string; currentTime: number }
  | { type: "pong"; timestamp: number }
  | { type: "user-latency-update"; userId: string; latency: number }
  | { type: "video-url"; url: string; userId: string; displayName: string };

// ─── REST API ──────────────────────────────────────────────────────

export interface CreateRoomRequest {
  name: string;
  password?: string;
}

export interface CreateRoomResponse {
  roomId: string;
  name: string;
}

export interface CreateRoomConflictResponse {
  error: "ROOM_EXISTS";
  message: string;
}

export interface RoomStateResponse {
  room: RoomState;
}

export interface RoomExistsResponse {
  exists: boolean;
}

export interface ApiErrorResponse {
  error: string;
}
